package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.39

import (
	"context"
	"fmt"
	"github.com/kloudlite/api/pkg/errors"
	"time"

	"github.com/kloudlite/api/apps/iot-console/internal/app/graph/generated"
	"github.com/kloudlite/api/apps/iot-console/internal/app/graph/model"
	"github.com/kloudlite/api/apps/iot-console/internal/entities"
	fn "github.com/kloudlite/api/pkg/functions"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
)

// BluePrintType is the resolver for the bluePrintType field.
func (r *iOTDeviceBlueprintResolver) BluePrintType(ctx context.Context, obj *entities.IOTDeviceBlueprint) (model.GithubComKloudliteAPIAppsIotConsoleInternalEntitiesBluePrintType, error) {
	if obj == nil {
		return "", errNilProject
	}
	var m model.GithubComKloudliteAPIAppsIotConsoleInternalEntitiesBluePrintType
	if err := fn.JsonConversion(obj.BluePrintType, &m); err != nil {
		return "", errors.NewE(err)
	}
	return m, nil
}

// CreationTime is the resolver for the creationTime field.
func (r *iOTDeviceBlueprintResolver) CreationTime(ctx context.Context, obj *entities.IOTDeviceBlueprint) (string, error) {
	if obj == nil {
		return "", errNilDeviceBlueprint
	}
	return obj.CreationTime.Format(time.RFC3339), nil
}

// Spec is the resolver for the spec field.
func (r *iOTDeviceBlueprintResolver) Spec(ctx context.Context, obj *entities.IOTDeviceBlueprint) (*model.GithubComKloudliteOperatorApisCrdsV1BlueprintSpec, error) {
	panic(fmt.Errorf("not implemented: Spec - spec"))
}

// Status is the resolver for the status field.
func (r *iOTDeviceBlueprintResolver) Status(ctx context.Context, obj *entities.IOTDeviceBlueprint) (*model.GithubComKloudliteOperatorApisCrdsV1BlueprintStatus, error) {
	panic(fmt.Errorf("not implemented: Status - status"))
}

// SyncStatus is the resolver for the syncStatus field.
func (r *iOTDeviceBlueprintResolver) SyncStatus(ctx context.Context, obj *entities.IOTDeviceBlueprint) (*model.GithubComKloudliteAPIPkgTypesSyncStatus, error) {
	panic(fmt.Errorf("not implemented: SyncStatus - syncStatus"))
}

// UpdateTime is the resolver for the updateTime field.
func (r *iOTDeviceBlueprintResolver) UpdateTime(ctx context.Context, obj *entities.IOTDeviceBlueprint) (string, error) {
	if obj == nil {
		return "", errNilDeviceBlueprint
	}
	return obj.UpdateTime.Format(time.RFC3339), nil
}

// BluePrintType is the resolver for the bluePrintType field.
func (r *iOTDeviceBlueprintInResolver) BluePrintType(ctx context.Context, obj *entities.IOTDeviceBlueprint, data model.GithubComKloudliteAPIAppsIotConsoleInternalEntitiesBluePrintType) error {
	if obj == nil {
		return errNilDeviceBlueprint
	}
	return fn.JsonConversion(data, &obj.BluePrintType)
}

// Metadata is the resolver for the metadata field.
func (r *iOTDeviceBlueprintInResolver) Metadata(ctx context.Context, obj *entities.IOTDeviceBlueprint, data *v1.ObjectMeta) error {
	panic(fmt.Errorf("not implemented: Metadata - metadata"))
}

// Spec is the resolver for the spec field.
func (r *iOTDeviceBlueprintInResolver) Spec(ctx context.Context, obj *entities.IOTDeviceBlueprint, data *model.GithubComKloudliteOperatorApisCrdsV1BlueprintSpecIn) error {
	panic(fmt.Errorf("not implemented: Spec - spec"))
}

// IOTDeviceBlueprint returns generated.IOTDeviceBlueprintResolver implementation.
func (r *Resolver) IOTDeviceBlueprint() generated.IOTDeviceBlueprintResolver {
	return &iOTDeviceBlueprintResolver{r}
}

// IOTDeviceBlueprintIn returns generated.IOTDeviceBlueprintInResolver implementation.
func (r *Resolver) IOTDeviceBlueprintIn() generated.IOTDeviceBlueprintInResolver {
	return &iOTDeviceBlueprintInResolver{r}
}

type iOTDeviceBlueprintResolver struct{ *Resolver }
type iOTDeviceBlueprintInResolver struct{ *Resolver }
