package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.28

import (
	"context"
	"time"

	"kloudlite.io/apps/container-registry/internal/app/graph/generated"
	"kloudlite.io/apps/container-registry/internal/domain/entities"
)

// CreationTime is the resolver for the creationTime field.
func (r *repositoryResolver) CreationTime(ctx context.Context, obj *entities.Repository) (string, error) {
	return obj.CreationTime.Format(time.RFC3339), nil
}

// ID is the resolver for the id field.
func (r *repositoryResolver) ID(ctx context.Context, obj *entities.Repository) (string, error) {
	return string(obj.Id), nil
}

// UpdateTime is the resolver for the updateTime field.
func (r *repositoryResolver) UpdateTime(ctx context.Context, obj *entities.Repository) (string, error) {
	return obj.UpdateTime.Format(time.RFC3339), nil
}

// Repository returns generated.RepositoryResolver implementation.
func (r *Resolver) Repository() generated.RepositoryResolver { return &repositoryResolver{r} }

type repositoryResolver struct{ *Resolver }
