name: Build Setup
runs:
  using: "composite"
  steps:

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set Docker tag
      id: tag
      uses: cytopia/docker-tag-action@v0.4.7

    - name: Setup Docker Cache
      uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true
      with:
        key: kl-platform-cache-{hash}
        restore-keys: |
          kl-platform-cache-

