package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.28

import (
	"context"
	"kloudlite.io/apps/dns/internal/app/graph/generated"
	"kloudlite.io/apps/dns/internal/app/graph/model"
	"kloudlite.io/pkg/repos"
)

// FindAccountByName is the resolver for the findAccountByName field.
func (r *entityResolver) FindAccountByName(ctx context.Context, name string) (*model.Account, error) {
	return &model.Account{
		Name: name,
	}, nil
}

// FindSiteByID is the resolver for the findSiteByID field.
func (r *entityResolver) FindSiteByID(ctx context.Context, id repos.ID) (*model.Site, error) {
	site, err := r.d.GetSite(ctx, string(id))
	if err != nil {
		return nil, err
	}
	return &model.Site{
		ID:          id,
		AccountName: site.AccountName,
		Domain:      site.Domain,
	}, nil
}

// Entity returns generated.EntityResolver implementation.
func (r *Resolver) Entity() generated.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
