// DO NOT EDIT. generated by "github.com/kloudlite/api/cmd/struct-json-path"

package field_constants

// constant vars generated for struct EmailConfig
const (
	EmailConfigEnabled     = "enabled"
	EmailConfigMailAddress = "mailAddress"
)

// constant vars generated for struct NotificationConf
const (
	NotificationConfEmailConfigurations            = "emailConfigurations"
	NotificationConfEmailConfigurationsEnabled     = "emailConfigurations.enabled"
	NotificationConfEmailConfigurationsMailAddress = "emailConfigurations.mailAddress"
	NotificationConfSlackConfigurations            = "slackConfigurations"
	NotificationConfSlackConfigurationsEnabled     = "slackConfigurations.enabled"
	NotificationConfSlackConfigurationsWebhook     = "slackConfigurations.webhook"
	NotificationConfTelegramConfigurations         = "telegramConfigurations"
	NotificationConfTelegramConfigurationsEnabled  = "telegramConfigurations.enabled"
)

// constant vars generated for struct SlackConfig
const (
	SlackConfigEnabled = "enabled"
	SlackConfigWebhook = "webhook"
)

// constant vars generated for struct Subscription
const (
	SubscriptionConfigurations                     = "configurations"
	SubscriptionConfigurationsAlertsEnabled        = "configurations.alertsEnabled"
	SubscriptionConfigurationsNotificationsEnabled = "configurations.notificationsEnabled"
	SubscriptionEnabled                            = "enabled"
	SubscriptionMailAddress                        = "mailAddress"
)

// constant vars generated for struct SubscriptionConf
const (
	SubscriptionConfAlertsEnabled        = "alertsEnabled"
	SubscriptionConfNotificationsEnabled = "notificationsEnabled"
)

// constant vars generated for struct TelegramConfig
const (
	TelegramConfigEnabled = "enabled"
)

// constant vars generated for struct
const (
	AccountName            = "accountName"
	CreatedBy              = "createdBy"
	CreatedByUserEmail     = "createdBy.userEmail"
	CreatedByUserId        = "createdBy.userId"
	CreatedByUserName      = "createdBy.userName"
	CreationTime           = "creationTime"
	Id                     = "id"
	LastUpdatedBy          = "lastUpdatedBy"
	LastUpdatedByUserEmail = "lastUpdatedBy.userEmail"
	LastUpdatedByUserId    = "lastUpdatedBy.userId"
	LastUpdatedByUserName  = "lastUpdatedBy.userName"
	MarkedForDeletion      = "markedForDeletion"
	RecordVersion          = "recordVersion"
	UpdateTime             = "updateTime"
)
