// DO NOT EDIT. generated by "github.com/kloudlite/api/cmd/struct-json-path"

package field_constants

// constant vars generated for struct Notification
const (
	NotificationAccountName                          = "accountName"
	NotificationCreationTime                         = "creationTime"
	NotificationId                                   = "id"
	NotificationMarkedForDeletion                    = "markedForDeletion"
	NotificationNotificationClusterParams            = "notificationClusterParams"
	NotificationNotificationClusterParamsClusterName = "notificationClusterParams.clusterName"
	NotificationNotificationEnvParams                = "notificationEnvParams"
	NotificationNotificationEnvParamsEnvName         = "notificationEnvParams.envName"
	NotificationNotificationType                     = "notificationType"
	NotificationRead                                 = "read"
	NotificationRecordVersion                        = "recordVersion"
	NotificationResourceType                         = "resourceType"
	NotificationUpdateTime                           = "updateTime"
)

// constant vars generated for struct NotificationClusterParams
const (
	NotificationClusterParamsClusterName = "clusterName"
)

// constant vars generated for struct NotificationEnvParams
const (
	NotificationEnvParamsEnvName = "envName"
)

// constant vars generated for struct
const ()
