// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"kloudlite.io/pkg/repos"
)

type Account struct {
	Name  string  `json:"name"`
	Sites []*Site `json:"sites"`
}

func (Account) IsEntity() {}

type Site struct {
	ID           repos.ID `json:"id"`
	RegionID     repos.ID `json:"regionId"`
	AccountName  string   `json:"accountName"`
	IsVerified   bool     `json:"isVerified"`
	Domain       string   `json:"domain"`
	CreationDate string   `json:"creationDate"`
	EdgeCname    string   `json:"edgeCname"`
}

func (Site) IsEntity() {}
