version: 3

dotenv:
  - .secrets/.env

includes:
  grpc:
    taskfile: ../../grpc-interfaces/Taskfile.yml
    dir: ../../grpc-interfaces/

vars:
  ImagePrefix: "ghcr.io/kloudlite/platform/apis"

tasks:
  proto:
    cmds:
      - task: grpc:build

  build:
    env:
      CGO_ENABLED: 0
      GOOS: linux
      GOARCH: amd64
    preconditions:
      - sh: '[ -n "{{.Out}}" ]'
        msg: var Out must have a value
    cmds:
      - go build -ldflags="-s -w" -o {{.Out}}
      - upx {{.Out}}

  run:
    dotenv:
      - .secrets/env
    cmds:
      - go run ./main.go

  docker-build:
    vars:
      APP: iam
      IMAGE: registry.kloudlite.io/kloudlite/{{.EnvName}}/{{.APP}}:{{.Tag}}
    preconditions:
      - sh: '[[ -n "{{.Tag}}" ]]'
        msg: 'var Tag must have a value'

      - sh: '[[ "{{.EnvName}}" == "development" ]] || [[ "{{.EnvName}}" == "staging" ]] ||  [[ "{{.EnvName}}" == "production" ]]'
        msg: 'var EnvName must have one of [development, staging, production] as its value'
    cmds:
      - docker buildx build -f ./Dockerfile -t {{.IMAGE}} . --build-arg APP={{.APP}} --platform linux/amd64  --build-context project-root=../..
      - docker push {{.IMAGE}}

  local-build:
    vars:
      APP: iam
      IMAGE: "{{.ImagePrefix}}/{{.APP}}:{{.Tag}}"
    preconditions:
      - sh: '[[ -n "{{.Tag}}" ]]'
        msg: 'var Tag must have a value'
    silent: true
    cmds:
      - |+
        tdir=$(mktemp -d)
        task build Out=$tdir/{{.APP}}

        docker buildx build -f ./Dockerfile.ci -t {{.IMAGE}} . --build-context builder=${tdir} --build-arg APP="{{.APP}}"
        docker push {{.IMAGE}}
        rm -rf $tdir
