package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"

	"github.com/kloudlite/api/apps/finance/internal/app/graph/generated"
	"github.com/kloudlite/api/apps/finance/internal/app/graph/model"
	"github.com/kloudlite/api/apps/finance/internal/entities"
)

// CreatedAt is the resolver for the createdAt field.
func (r *paymentResolver) CreatedAt(ctx context.Context, obj *entities.Payment) (string, error) {
	panic(fmt.Errorf("not implemented: CreatedAt - createdAt"))
}

// CreationTime is the resolver for the creationTime field.
func (r *paymentResolver) CreationTime(ctx context.Context, obj *entities.Payment) (string, error) {
	panic(fmt.Errorf("not implemented: CreationTime - creationTime"))
}

// PaymentLink is the resolver for the payment_link field.
func (r *paymentResolver) PaymentLink(ctx context.Context, obj *entities.Payment) (*model.GithubComKloudliteAPIAppsFinanceInternalEntitiesPaymentLink, error) {
	panic(fmt.Errorf("not implemented: PaymentLink - payment_link"))
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *paymentResolver) UpdatedAt(ctx context.Context, obj *entities.Payment) (string, error) {
	panic(fmt.Errorf("not implemented: UpdatedAt - updatedAt"))
}

// UpdateTime is the resolver for the updateTime field.
func (r *paymentResolver) UpdateTime(ctx context.Context, obj *entities.Payment) (string, error) {
	panic(fmt.Errorf("not implemented: UpdateTime - updateTime"))
}

// PaymentLink is the resolver for the payment_link field.
func (r *paymentInResolver) PaymentLink(ctx context.Context, obj *entities.Payment, data *model.GithubComKloudliteAPIAppsFinanceInternalEntitiesPaymentLinkIn) error {
	panic(fmt.Errorf("not implemented: PaymentLink - payment_link"))
}

// Payment returns generated.PaymentResolver implementation.
func (r *Resolver) Payment() generated.PaymentResolver { return &paymentResolver{r} }

// PaymentIn returns generated.PaymentInResolver implementation.
func (r *Resolver) PaymentIn() generated.PaymentInResolver { return &paymentInResolver{r} }

type paymentResolver struct{ *Resolver }
type paymentInResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
func (r *paymentResolver) Status(ctx context.Context, obj *entities.Payment) (model.GithubComKloudliteAPIAppsFinanceInternalEntitiesPaymentStatus, error) {
	panic(fmt.Errorf("not implemented: Status - status"))
}
func (r *paymentResolver) WalletID(ctx context.Context, obj *entities.Payment) (string, error) {
	panic(fmt.Errorf("not implemented: WalletID - walletId"))
}
func (r *paymentInResolver) WalletID(ctx context.Context, obj *entities.Payment, data string) error {
	panic(fmt.Errorf("not implemented: WalletID - walletId"))
}
