package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"
	"time"

	"github.com/kloudlite/api/apps/finance/internal/app/graph/generated"
	"github.com/kloudlite/api/apps/finance/internal/app/graph/model"
	"github.com/kloudlite/api/apps/finance/internal/entities"
	"github.com/kloudlite/api/pkg/functions"
)

// CreatedAt is the resolver for the createdAt field.
func (r *paymentResolver) CreatedAt(ctx context.Context, obj *entities.Payment) (string, error) {
	if obj == nil {
		return "", fmt.Errorf("object is nil")
	}

	return obj.CreatedAt.Format(time.RFC3339), nil
}

// CreationTime is the resolver for the creationTime field.
func (r *paymentResolver) CreationTime(ctx context.Context, obj *entities.Payment) (string, error) {
	if obj == nil {
		return "", fmt.Errorf("object is nil")
	}

	return obj.CreationTime.Format(time.RFC3339), nil
}

// PaymentLink is the resolver for the payment_link field.
func (r *paymentResolver) PaymentLink(ctx context.Context, obj *entities.Payment) (*model.GithubComKloudliteAPIAppsFinanceInternalEntitiesPaymentLink, error) {
	if obj == nil {
		return nil, fmt.Errorf("object is nil")
	}

	return functions.JsonConvertP[model.GithubComKloudliteAPIAppsFinanceInternalEntitiesPaymentLink](obj.Link)
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *paymentResolver) UpdatedAt(ctx context.Context, obj *entities.Payment) (string, error) {
	if obj == nil {
		return "", fmt.Errorf("object is nil")
	}

	return obj.UpdatedAt.Format(time.RFC3339), nil
}

// UpdateTime is the resolver for the updateTime field.
func (r *paymentResolver) UpdateTime(ctx context.Context, obj *entities.Payment) (string, error) {
	if obj == nil {
		return "", fmt.Errorf("object is nil")
	}

	return obj.UpdateTime.Format(time.RFC3339), nil
}

// PaymentLink is the resolver for the payment_link field.
func (r *paymentInResolver) PaymentLink(ctx context.Context, obj *entities.Payment, data *model.GithubComKloudliteAPIAppsFinanceInternalEntitiesPaymentLinkIn) error {
	if obj == nil {
		return fmt.Errorf("object is nil")
	}

	pl, err := functions.JsonConvertP[entities.PaymentLink](data)
	if err != nil {
		return err
	}

	obj.Link = pl
	return nil
}

// Payment returns generated.PaymentResolver implementation.
func (r *Resolver) Payment() generated.PaymentResolver { return &paymentResolver{r} }

// PaymentIn returns generated.PaymentInResolver implementation.
func (r *Resolver) PaymentIn() generated.PaymentInResolver { return &paymentInResolver{r} }

type paymentResolver struct{ *Resolver }
type paymentInResolver struct{ *Resolver }
