package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"

	"github.com/kloudlite/api/apps/finance/internal/app/graph/generated"
	"github.com/kloudlite/api/apps/finance/internal/entities"
)

// CreationTime is the resolver for the creationTime field.
func (r *paymentResolver) CreationTime(ctx context.Context, obj *entities.Payment) (string, error) {
	panic(fmt.Errorf("not implemented: CreationTime - creationTime"))
}

// UpdateTime is the resolver for the updateTime field.
func (r *paymentResolver) UpdateTime(ctx context.Context, obj *entities.Payment) (string, error) {
	panic(fmt.Errorf("not implemented: UpdateTime - updateTime"))
}

// Payment returns generated.PaymentResolver implementation.
func (r *Resolver) Payment() generated.PaymentResolver { return &paymentResolver{r} }

type paymentResolver struct{ *Resolver }
