package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"

	"github.com/kloudlite/api/apps/finance/internal/app/graph/generated"
	"github.com/kloudlite/api/apps/finance/internal/app/graph/model"
	"github.com/kloudlite/api/apps/finance/internal/entities"
)

// CreatedBy is the resolver for the createdBy field.
func (r *transactionResolver) CreatedBy(ctx context.Context, obj *entities.Transaction) (*model.GithubComKloudliteAPICommonCreatedOrUpdatedBy, error) {
	panic(fmt.Errorf("not implemented: CreatedBy - createdBy"))
}

// CreationTime is the resolver for the creationTime field.
func (r *transactionResolver) CreationTime(ctx context.Context, obj *entities.Transaction) (string, error) {
	panic(fmt.Errorf("not implemented: CreationTime - creationTime"))
}

// LastUpdatedBy is the resolver for the lastUpdatedBy field.
func (r *transactionResolver) LastUpdatedBy(ctx context.Context, obj *entities.Transaction) (*model.GithubComKloudliteAPICommonCreatedOrUpdatedBy, error) {
	panic(fmt.Errorf("not implemented: LastUpdatedBy - lastUpdatedBy"))
}

// UpdateTime is the resolver for the updateTime field.
func (r *transactionResolver) UpdateTime(ctx context.Context, obj *entities.Transaction) (string, error) {
	panic(fmt.Errorf("not implemented: UpdateTime - updateTime"))
}

// Transaction returns generated.TransactionResolver implementation.
func (r *Resolver) Transaction() generated.TransactionResolver { return &transactionResolver{r} }

type transactionResolver struct{ *Resolver }
