package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"

	"github.com/kloudlite/api/apps/finance/internal/app/graph/generated"
	"github.com/kloudlite/api/apps/finance/internal/app/graph/model"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
)

// objectMeta is the resolver for the metadata field.
func (r *usesResolver) objectMeta(ctx context.Context, obj *model.Uses) (*v1.ObjectMeta, error) {
	panic(fmt.Errorf("not implemented: objectMeta - metadata"))
}

// Uses returns generated.UsesResolver implementation.
func (r *Resolver) Uses() generated.UsesResolver { return &usesResolver{r} }

type usesResolver struct{ *Resolver }
