// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AppSpec struct {
	Freeze         *bool                  `json:"freeze,omitempty"`
	Region         *string                `json:"region,omitempty"`
	ServiceAccount *string                `json:"serviceAccount,omitempty"`
	DisplayName    *string                `json:"displayName,omitempty"`
	Hpa            *AppSpecHpa            `json:"hpa,omitempty"`
	Intercept      *AppSpecIntercept      `json:"intercept,omitempty"`
	NodeSelector   map[string]interface{} `json:"nodeSelector,omitempty"`
	Replicas       *int                   `json:"replicas,omitempty"`
	Services       []*AppSpecServices     `json:"services,omitempty"`
	Tolerations    []*AppSpecTolerations  `json:"tolerations,omitempty"`
	Containers     []*AppSpecContainers   `json:"containers"`
}

type AppSpecContainers struct {
	ResourceCPU     *AppSpecContainersResourceCPU    `json:"resourceCpu,omitempty"`
	Volumes         []*AppSpecContainersVolumes      `json:"volumes,omitempty"`
	Command         []*string                        `json:"command,omitempty"`
	ImagePullPolicy *string                          `json:"imagePullPolicy,omitempty"`
	LivenessProbe   *AppSpecContainersLivenessProbe  `json:"livenessProbe,omitempty"`
	Name            string                           `json:"name"`
	ReadinessProbe  *AppSpecContainersReadinessProbe `json:"readinessProbe,omitempty"`
	Args            []*string                        `json:"args,omitempty"`
	Env             []*AppSpecContainersEnv          `json:"env,omitempty"`
	EnvFrom         []*AppSpecContainersEnvFrom      `json:"envFrom,omitempty"`
	Image           string                           `json:"image"`
	ResourceMemory  *AppSpecContainersResourceMemory `json:"resourceMemory,omitempty"`
}

type AppSpecContainersEnv struct {
	RefKey   *string `json:"refKey,omitempty"`
	RefName  *string `json:"refName,omitempty"`
	Type     *string `json:"type,omitempty"`
	Value    *string `json:"value,omitempty"`
	Key      string  `json:"key"`
	Optional *bool   `json:"optional,omitempty"`
}

type AppSpecContainersEnvFrom struct {
	RefName string `json:"refName"`
	Type    string `json:"type"`
}

type AppSpecContainersEnvFromIn struct {
	RefName string `json:"refName"`
	Type    string `json:"type"`
}

type AppSpecContainersEnvIn struct {
	RefKey   *string `json:"refKey,omitempty"`
	RefName  *string `json:"refName,omitempty"`
	Type     *string `json:"type,omitempty"`
	Value    *string `json:"value,omitempty"`
	Key      string  `json:"key"`
	Optional *bool   `json:"optional,omitempty"`
}

type AppSpecContainersIn struct {
	ResourceCPU     *AppSpecContainersResourceCPUIn    `json:"resourceCpu,omitempty"`
	Volumes         []*AppSpecContainersVolumesIn      `json:"volumes,omitempty"`
	Command         []*string                          `json:"command,omitempty"`
	ImagePullPolicy *string                            `json:"imagePullPolicy,omitempty"`
	LivenessProbe   *AppSpecContainersLivenessProbeIn  `json:"livenessProbe,omitempty"`
	Name            string                             `json:"name"`
	ReadinessProbe  *AppSpecContainersReadinessProbeIn `json:"readinessProbe,omitempty"`
	Args            []*string                          `json:"args,omitempty"`
	Env             []*AppSpecContainersEnvIn          `json:"env,omitempty"`
	EnvFrom         []*AppSpecContainersEnvFromIn      `json:"envFrom,omitempty"`
	Image           string                             `json:"image"`
	ResourceMemory  *AppSpecContainersResourceMemoryIn `json:"resourceMemory,omitempty"`
}

type AppSpecContainersLivenessProbe struct {
	Type             string                                 `json:"type"`
	FailureThreshold *int                                   `json:"failureThreshold,omitempty"`
	HTTPGet          *AppSpecContainersLivenessProbeHTTPGet `json:"httpGet,omitempty"`
	InitialDelay     *int                                   `json:"initialDelay,omitempty"`
	Interval         *int                                   `json:"interval,omitempty"`
	Shell            *AppSpecContainersLivenessProbeShell   `json:"shell,omitempty"`
	TCP              *AppSpecContainersLivenessProbeTCP     `json:"tcp,omitempty"`
}

type AppSpecContainersLivenessProbeHTTPGet struct {
	HTTPHeaders map[string]interface{} `json:"httpHeaders,omitempty"`
	Path        string                 `json:"path"`
	Port        int                    `json:"port"`
}

type AppSpecContainersLivenessProbeHTTPGetIn struct {
	HTTPHeaders map[string]interface{} `json:"httpHeaders,omitempty"`
	Path        string                 `json:"path"`
	Port        int                    `json:"port"`
}

type AppSpecContainersLivenessProbeIn struct {
	Type             string                                   `json:"type"`
	FailureThreshold *int                                     `json:"failureThreshold,omitempty"`
	HTTPGet          *AppSpecContainersLivenessProbeHTTPGetIn `json:"httpGet,omitempty"`
	InitialDelay     *int                                     `json:"initialDelay,omitempty"`
	Interval         *int                                     `json:"interval,omitempty"`
	Shell            *AppSpecContainersLivenessProbeShellIn   `json:"shell,omitempty"`
	TCP              *AppSpecContainersLivenessProbeTCPIn     `json:"tcp,omitempty"`
}

type AppSpecContainersLivenessProbeShell struct {
	Command []*string `json:"command,omitempty"`
}

type AppSpecContainersLivenessProbeShellIn struct {
	Command []*string `json:"command,omitempty"`
}

type AppSpecContainersLivenessProbeTCP struct {
	Port int `json:"port"`
}

type AppSpecContainersLivenessProbeTCPIn struct {
	Port int `json:"port"`
}

type AppSpecContainersReadinessProbe struct {
	TCP              *AppSpecContainersReadinessProbeTCP     `json:"tcp,omitempty"`
	Type             string                                  `json:"type"`
	FailureThreshold *int                                    `json:"failureThreshold,omitempty"`
	HTTPGet          *AppSpecContainersReadinessProbeHTTPGet `json:"httpGet,omitempty"`
	InitialDelay     *int                                    `json:"initialDelay,omitempty"`
	Interval         *int                                    `json:"interval,omitempty"`
	Shell            *AppSpecContainersReadinessProbeShell   `json:"shell,omitempty"`
}

type AppSpecContainersReadinessProbeHTTPGet struct {
	HTTPHeaders map[string]interface{} `json:"httpHeaders,omitempty"`
	Path        string                 `json:"path"`
	Port        int                    `json:"port"`
}

type AppSpecContainersReadinessProbeHTTPGetIn struct {
	HTTPHeaders map[string]interface{} `json:"httpHeaders,omitempty"`
	Path        string                 `json:"path"`
	Port        int                    `json:"port"`
}

type AppSpecContainersReadinessProbeIn struct {
	TCP              *AppSpecContainersReadinessProbeTCPIn     `json:"tcp,omitempty"`
	Type             string                                    `json:"type"`
	FailureThreshold *int                                      `json:"failureThreshold,omitempty"`
	HTTPGet          *AppSpecContainersReadinessProbeHTTPGetIn `json:"httpGet,omitempty"`
	InitialDelay     *int                                      `json:"initialDelay,omitempty"`
	Interval         *int                                      `json:"interval,omitempty"`
	Shell            *AppSpecContainersReadinessProbeShellIn   `json:"shell,omitempty"`
}

type AppSpecContainersReadinessProbeShell struct {
	Command []*string `json:"command,omitempty"`
}

type AppSpecContainersReadinessProbeShellIn struct {
	Command []*string `json:"command,omitempty"`
}

type AppSpecContainersReadinessProbeTCP struct {
	Port int `json:"port"`
}

type AppSpecContainersReadinessProbeTCPIn struct {
	Port int `json:"port"`
}

type AppSpecContainersResourceCPU struct {
	Min *string `json:"min,omitempty"`
	Max *string `json:"max,omitempty"`
}

type AppSpecContainersResourceCPUIn struct {
	Min *string `json:"min,omitempty"`
	Max *string `json:"max,omitempty"`
}

type AppSpecContainersResourceMemory struct {
	Max *string `json:"max,omitempty"`
	Min *string `json:"min,omitempty"`
}

type AppSpecContainersResourceMemoryIn struct {
	Max *string `json:"max,omitempty"`
	Min *string `json:"min,omitempty"`
}

type AppSpecContainersVolumes struct {
	RefName   string                           `json:"refName"`
	Type      string                           `json:"type"`
	Items     []*AppSpecContainersVolumesItems `json:"items,omitempty"`
	MountPath string                           `json:"mountPath"`
}

type AppSpecContainersVolumesIn struct {
	RefName   string                             `json:"refName"`
	Type      string                             `json:"type"`
	Items     []*AppSpecContainersVolumesItemsIn `json:"items,omitempty"`
	MountPath string                             `json:"mountPath"`
}

type AppSpecContainersVolumesItems struct {
	FileName *string `json:"fileName,omitempty"`
	Key      string  `json:"key"`
}

type AppSpecContainersVolumesItemsIn struct {
	FileName *string `json:"fileName,omitempty"`
	Key      string  `json:"key"`
}

type AppSpecHpa struct {
	MaxReplicas     *int  `json:"maxReplicas,omitempty"`
	MinReplicas     *int  `json:"minReplicas,omitempty"`
	ThresholdCPU    *int  `json:"thresholdCpu,omitempty"`
	ThresholdMemory *int  `json:"thresholdMemory,omitempty"`
	Enabled         *bool `json:"enabled,omitempty"`
}

type AppSpecHpaIn struct {
	MaxReplicas     *int  `json:"maxReplicas,omitempty"`
	MinReplicas     *int  `json:"minReplicas,omitempty"`
	ThresholdCPU    *int  `json:"thresholdCpu,omitempty"`
	ThresholdMemory *int  `json:"thresholdMemory,omitempty"`
	Enabled         *bool `json:"enabled,omitempty"`
}

type AppSpecIn struct {
	Freeze         *bool                   `json:"freeze,omitempty"`
	Region         *string                 `json:"region,omitempty"`
	ServiceAccount *string                 `json:"serviceAccount,omitempty"`
	DisplayName    *string                 `json:"displayName,omitempty"`
	Hpa            *AppSpecHpaIn           `json:"hpa,omitempty"`
	Intercept      *AppSpecInterceptIn     `json:"intercept,omitempty"`
	NodeSelector   map[string]interface{}  `json:"nodeSelector,omitempty"`
	Replicas       *int                    `json:"replicas,omitempty"`
	Services       []*AppSpecServicesIn    `json:"services,omitempty"`
	Tolerations    []*AppSpecTolerationsIn `json:"tolerations,omitempty"`
	Containers     []*AppSpecContainersIn  `json:"containers"`
}

type AppSpecIntercept struct {
	Enabled  bool   `json:"enabled"`
	ToDevice string `json:"toDevice"`
}

type AppSpecInterceptIn struct {
	Enabled  bool   `json:"enabled"`
	ToDevice string `json:"toDevice"`
}

type AppSpecServices struct {
	Name       *string `json:"name,omitempty"`
	Port       int     `json:"port"`
	TargetPort *int    `json:"targetPort,omitempty"`
	Type       *string `json:"type,omitempty"`
}

type AppSpecServicesIn struct {
	Name       *string `json:"name,omitempty"`
	Port       int     `json:"port"`
	TargetPort *int    `json:"targetPort,omitempty"`
	Type       *string `json:"type,omitempty"`
}

type AppSpecTolerations struct {
	Effect            *string `json:"effect,omitempty"`
	Key               *string `json:"key,omitempty"`
	Operator          *string `json:"operator,omitempty"`
	TolerationSeconds *int    `json:"tolerationSeconds,omitempty"`
	Value             *string `json:"value,omitempty"`
}

type AppSpecTolerationsIn struct {
	Effect            *string `json:"effect,omitempty"`
	Key               *string `json:"key,omitempty"`
	Operator          *string `json:"operator,omitempty"`
	TolerationSeconds *int    `json:"tolerationSeconds,omitempty"`
	Value             *string `json:"value,omitempty"`
}

type EnvironmentSpec struct {
	RouterBaseDomain *string `json:"routerBaseDomain,omitempty"`
	AccountID        string  `json:"accountId"`
	BlueprintName    *string `json:"blueprintName,omitempty"`
	ProjectName      string  `json:"projectName"`
}

type EnvironmentSpecIn struct {
	RouterBaseDomain *string `json:"routerBaseDomain,omitempty"`
	AccountID        string  `json:"accountId"`
	BlueprintName    *string `json:"blueprintName,omitempty"`
	ProjectName      string  `json:"projectName"`
}

type ManagedResourceSpec struct {
	Inputs   map[string]interface{}       `json:"inputs,omitempty"`
	MresKind *ManagedResourceSpecMresKind `json:"mresKind"`
	MsvcRef  *ManagedResourceSpecMsvcRef  `json:"msvcRef"`
}

type ManagedResourceSpecIn struct {
	Inputs   map[string]interface{}         `json:"inputs,omitempty"`
	MresKind *ManagedResourceSpecMresKindIn `json:"mresKind"`
	MsvcRef  *ManagedResourceSpecMsvcRefIn  `json:"msvcRef"`
}

type ManagedResourceSpecMresKind struct {
	Kind string `json:"kind"`
}

type ManagedResourceSpecMresKindIn struct {
	Kind string `json:"kind"`
}

type ManagedResourceSpecMsvcRef struct {
	APIVersion string  `json:"apiVersion"`
	Kind       *string `json:"kind,omitempty"`
	Name       string  `json:"name"`
}

type ManagedResourceSpecMsvcRefIn struct {
	APIVersion string  `json:"apiVersion"`
	Kind       *string `json:"kind,omitempty"`
	Name       string  `json:"name"`
}

type ManagedServiceSpec struct {
	Inputs       map[string]interface{}           `json:"inputs,omitempty"`
	MsvcKind     *ManagedServiceSpecMsvcKind      `json:"msvcKind"`
	NodeSelector map[string]interface{}           `json:"nodeSelector,omitempty"`
	Region       *string                          `json:"region,omitempty"`
	Tolerations  []*ManagedServiceSpecTolerations `json:"tolerations,omitempty"`
}

type ManagedServiceSpecIn struct {
	Inputs       map[string]interface{}             `json:"inputs,omitempty"`
	MsvcKind     *ManagedServiceSpecMsvcKindIn      `json:"msvcKind"`
	NodeSelector map[string]interface{}             `json:"nodeSelector,omitempty"`
	Region       *string                            `json:"region,omitempty"`
	Tolerations  []*ManagedServiceSpecTolerationsIn `json:"tolerations,omitempty"`
}

type ManagedServiceSpecMsvcKind struct {
	APIVersion string  `json:"apiVersion"`
	Kind       *string `json:"kind,omitempty"`
}

type ManagedServiceSpecMsvcKindIn struct {
	APIVersion string  `json:"apiVersion"`
	Kind       *string `json:"kind,omitempty"`
}

type ManagedServiceSpecTolerations struct {
	Effect            *string `json:"effect,omitempty"`
	Key               *string `json:"key,omitempty"`
	Operator          *string `json:"operator,omitempty"`
	TolerationSeconds *int    `json:"tolerationSeconds,omitempty"`
	Value             *string `json:"value,omitempty"`
}

type ManagedServiceSpecTolerationsIn struct {
	Effect            *string `json:"effect,omitempty"`
	Key               *string `json:"key,omitempty"`
	Operator          *string `json:"operator,omitempty"`
	TolerationSeconds *int    `json:"tolerationSeconds,omitempty"`
	Value             *string `json:"value,omitempty"`
}

type ProjectSpec struct {
	AccountName     string  `json:"accountName"`
	ClusterName     string  `json:"clusterName"`
	DisplayName     *string `json:"displayName,omitempty"`
	Logo            *string `json:"logo,omitempty"`
	TargetNamespace *string `json:"targetNamespace,omitempty"`
}

type ProjectSpecIn struct {
	AccountName     string  `json:"accountName"`
	ClusterName     string  `json:"clusterName"`
	DisplayName     *string `json:"displayName,omitempty"`
	Logo            *string `json:"logo,omitempty"`
	TargetNamespace *string `json:"targetNamespace,omitempty"`
}

type RouterSpec struct {
	Routes          []*RouterSpecRoutes  `json:"routes,omitempty"`
	BackendProtocol *string              `json:"backendProtocol,omitempty"`
	BasicAuth       *RouterSpecBasicAuth `json:"basicAuth,omitempty"`
	Domains         []*string            `json:"domains"`
	MaxBodySizeInMb *int                 `json:"maxBodySizeInMB,omitempty"`
	Region          *string              `json:"region,omitempty"`
	Cors            *RouterSpecCors      `json:"cors,omitempty"`
	HTTPS           *RouterSpecHTTPS     `json:"https,omitempty"`
	IngressClass    *string              `json:"ingressClass,omitempty"`
	RateLimit       *RouterSpecRateLimit `json:"rateLimit,omitempty"`
}

type RouterSpecBasicAuth struct {
	Enabled    bool    `json:"enabled"`
	SecretName *string `json:"secretName,omitempty"`
	Username   *string `json:"username,omitempty"`
}

type RouterSpecBasicAuthIn struct {
	Enabled    bool    `json:"enabled"`
	SecretName *string `json:"secretName,omitempty"`
	Username   *string `json:"username,omitempty"`
}

type RouterSpecCors struct {
	AllowCredentials *bool     `json:"allowCredentials,omitempty"`
	Enabled          *bool     `json:"enabled,omitempty"`
	Origins          []*string `json:"origins,omitempty"`
}

type RouterSpecCorsIn struct {
	AllowCredentials *bool     `json:"allowCredentials,omitempty"`
	Enabled          *bool     `json:"enabled,omitempty"`
	Origins          []*string `json:"origins,omitempty"`
}

type RouterSpecHTTPS struct {
	ClusterIssuer *string `json:"clusterIssuer,omitempty"`
	Enabled       bool    `json:"enabled"`
	ForceRedirect *bool   `json:"forceRedirect,omitempty"`
}

type RouterSpecHTTPSIn struct {
	ClusterIssuer *string `json:"clusterIssuer,omitempty"`
	Enabled       bool    `json:"enabled"`
	ForceRedirect *bool   `json:"forceRedirect,omitempty"`
}

type RouterSpecIn struct {
	Routes          []*RouterSpecRoutesIn  `json:"routes,omitempty"`
	BackendProtocol *string                `json:"backendProtocol,omitempty"`
	BasicAuth       *RouterSpecBasicAuthIn `json:"basicAuth,omitempty"`
	Domains         []*string              `json:"domains"`
	MaxBodySizeInMb *int                   `json:"maxBodySizeInMB,omitempty"`
	Region          *string                `json:"region,omitempty"`
	Cors            *RouterSpecCorsIn      `json:"cors,omitempty"`
	HTTPS           *RouterSpecHTTPSIn     `json:"https,omitempty"`
	IngressClass    *string                `json:"ingressClass,omitempty"`
	RateLimit       *RouterSpecRateLimitIn `json:"rateLimit,omitempty"`
}

type RouterSpecRateLimit struct {
	Connections *int  `json:"connections,omitempty"`
	Enabled     *bool `json:"enabled,omitempty"`
	Rpm         *int  `json:"rpm,omitempty"`
	Rps         *int  `json:"rps,omitempty"`
}

type RouterSpecRateLimitIn struct {
	Connections *int  `json:"connections,omitempty"`
	Enabled     *bool `json:"enabled,omitempty"`
	Rpm         *int  `json:"rpm,omitempty"`
	Rps         *int  `json:"rps,omitempty"`
}

type RouterSpecRoutes struct {
	Path    string  `json:"path"`
	Port    int     `json:"port"`
	Rewrite *bool   `json:"rewrite,omitempty"`
	App     *string `json:"app,omitempty"`
	Lambda  *string `json:"lambda,omitempty"`
}

type RouterSpecRoutesIn struct {
	Path    string  `json:"path"`
	Port    int     `json:"port"`
	Rewrite *bool   `json:"rewrite,omitempty"`
	App     *string `json:"app,omitempty"`
	Lambda  *string `json:"lambda,omitempty"`
}
