// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type GithubComKloudliteOperatorApisCrdsV1AppSpecContainers struct {
	Args            []*string                                                            `json:"args,omitempty"`
	Command         []*string                                                            `json:"command,omitempty"`
	Env             []*GithubComKloudliteOperatorApisCrdsV1AppSpecContainersEnv          `json:"env,omitempty"`
	EnvFrom         []*GithubComKloudliteOperatorApisCrdsV1AppSpecContainersEnvFrom      `json:"envFrom,omitempty"`
	Image           string                                                               `json:"image"`
	ImagePullPolicy *string                                                              `json:"imagePullPolicy,omitempty"`
	LivenessProbe   *GithubComKloudliteOperatorApisCrdsV1AppSpecContainersLivenessProbe  `json:"livenessProbe,omitempty"`
	Name            string                                                               `json:"name"`
	ReadinessProbe  *GithubComKloudliteOperatorApisCrdsV1AppSpecContainersReadinessProbe `json:"readinessProbe,omitempty"`
	ResourceCPU     *GithubComKloudliteOperatorApisCrdsV1AppSpecContainersResourceCPU    `json:"resourceCpu,omitempty"`
	ResourceMemory  *GithubComKloudliteOperatorApisCrdsV1AppSpecContainersResourceMemory `json:"resourceMemory,omitempty"`
	Volumes         []*GithubComKloudliteOperatorApisCrdsV1AppSpecContainersVolumes      `json:"volumes,omitempty"`
}

type GithubComKloudliteOperatorApisCrdsV1AppSpecContainersEnv struct {
	Key      string  `json:"key"`
	Optional *bool   `json:"optional,omitempty"`
	RefKey   *string `json:"refKey,omitempty"`
	RefName  *string `json:"refName,omitempty"`
	Type     *string `json:"type,omitempty"`
	Value    *string `json:"value,omitempty"`
}

type GithubComKloudliteOperatorApisCrdsV1AppSpecContainersEnvFrom struct {
	RefName string `json:"refName"`
	Type    string `json:"type"`
}

type GithubComKloudliteOperatorApisCrdsV1AppSpecContainersEnvFromIn struct {
	RefName string `json:"refName"`
	Type    string `json:"type"`
}

type GithubComKloudliteOperatorApisCrdsV1AppSpecContainersEnvIn struct {
	Key      string  `json:"key"`
	Optional *bool   `json:"optional,omitempty"`
	RefKey   *string `json:"refKey,omitempty"`
	RefName  *string `json:"refName,omitempty"`
	Type     *string `json:"type,omitempty"`
	Value    *string `json:"value,omitempty"`
}

type GithubComKloudliteOperatorApisCrdsV1AppSpecContainersIn struct {
	Args            []*string                                                              `json:"args,omitempty"`
	Command         []*string                                                              `json:"command,omitempty"`
	Env             []*GithubComKloudliteOperatorApisCrdsV1AppSpecContainersEnvIn          `json:"env,omitempty"`
	EnvFrom         []*GithubComKloudliteOperatorApisCrdsV1AppSpecContainersEnvFromIn      `json:"envFrom,omitempty"`
	Image           string                                                                 `json:"image"`
	ImagePullPolicy *string                                                                `json:"imagePullPolicy,omitempty"`
	LivenessProbe   *GithubComKloudliteOperatorApisCrdsV1AppSpecContainersLivenessProbeIn  `json:"livenessProbe,omitempty"`
	Name            string                                                                 `json:"name"`
	ReadinessProbe  *GithubComKloudliteOperatorApisCrdsV1AppSpecContainersReadinessProbeIn `json:"readinessProbe,omitempty"`
	ResourceCPU     *GithubComKloudliteOperatorApisCrdsV1AppSpecContainersResourceCPUIn    `json:"resourceCpu,omitempty"`
	ResourceMemory  *GithubComKloudliteOperatorApisCrdsV1AppSpecContainersResourceMemoryIn `json:"resourceMemory,omitempty"`
	Volumes         []*GithubComKloudliteOperatorApisCrdsV1AppSpecContainersVolumesIn      `json:"volumes,omitempty"`
}

type GithubComKloudliteOperatorApisCrdsV1AppSpecContainersLivenessProbe struct {
	FailureThreshold *int                                                                       `json:"failureThreshold,omitempty"`
	HTTPGet          *GithubComKloudliteOperatorApisCrdsV1AppSpecContainersLivenessProbeHTTPGet `json:"httpGet,omitempty"`
	InitialDelay     *int                                                                       `json:"initialDelay,omitempty"`
	Interval         *int                                                                       `json:"interval,omitempty"`
	Shell            *GithubComKloudliteOperatorApisCrdsV1AppSpecContainersLivenessProbeShell   `json:"shell,omitempty"`
	TCP              *GithubComKloudliteOperatorApisCrdsV1AppSpecContainersLivenessProbeTCP     `json:"tcp,omitempty"`
	Type             string                                                                     `json:"type"`
}

type GithubComKloudliteOperatorApisCrdsV1AppSpecContainersLivenessProbeHTTPGet struct {
	HTTPHeaders map[string]interface{} `json:"httpHeaders,omitempty"`
	Path        string                 `json:"path"`
	Port        int                    `json:"port"`
}

type GithubComKloudliteOperatorApisCrdsV1AppSpecContainersLivenessProbeHTTPGetIn struct {
	HTTPHeaders map[string]interface{} `json:"httpHeaders,omitempty"`
	Path        string                 `json:"path"`
	Port        int                    `json:"port"`
}

type GithubComKloudliteOperatorApisCrdsV1AppSpecContainersLivenessProbeIn struct {
	FailureThreshold *int                                                                         `json:"failureThreshold,omitempty"`
	HTTPGet          *GithubComKloudliteOperatorApisCrdsV1AppSpecContainersLivenessProbeHTTPGetIn `json:"httpGet,omitempty"`
	InitialDelay     *int                                                                         `json:"initialDelay,omitempty"`
	Interval         *int                                                                         `json:"interval,omitempty"`
	Shell            *GithubComKloudliteOperatorApisCrdsV1AppSpecContainersLivenessProbeShellIn   `json:"shell,omitempty"`
	TCP              *GithubComKloudliteOperatorApisCrdsV1AppSpecContainersLivenessProbeTCPIn     `json:"tcp,omitempty"`
	Type             string                                                                       `json:"type"`
}

type GithubComKloudliteOperatorApisCrdsV1AppSpecContainersLivenessProbeShell struct {
	Command []*string `json:"command,omitempty"`
}

type GithubComKloudliteOperatorApisCrdsV1AppSpecContainersLivenessProbeShellIn struct {
	Command []*string `json:"command,omitempty"`
}

type GithubComKloudliteOperatorApisCrdsV1AppSpecContainersLivenessProbeTCP struct {
	Port int `json:"port"`
}

type GithubComKloudliteOperatorApisCrdsV1AppSpecContainersLivenessProbeTCPIn struct {
	Port int `json:"port"`
}

type GithubComKloudliteOperatorApisCrdsV1AppSpecContainersReadinessProbe struct {
	FailureThreshold *int                                                                        `json:"failureThreshold,omitempty"`
	HTTPGet          *GithubComKloudliteOperatorApisCrdsV1AppSpecContainersReadinessProbeHTTPGet `json:"httpGet,omitempty"`
	InitialDelay     *int                                                                        `json:"initialDelay,omitempty"`
	Interval         *int                                                                        `json:"interval,omitempty"`
	Shell            *GithubComKloudliteOperatorApisCrdsV1AppSpecContainersReadinessProbeShell   `json:"shell,omitempty"`
	TCP              *GithubComKloudliteOperatorApisCrdsV1AppSpecContainersReadinessProbeTCP     `json:"tcp,omitempty"`
	Type             string                                                                      `json:"type"`
}

type GithubComKloudliteOperatorApisCrdsV1AppSpecContainersReadinessProbeHTTPGet struct {
	HTTPHeaders map[string]interface{} `json:"httpHeaders,omitempty"`
	Path        string                 `json:"path"`
	Port        int                    `json:"port"`
}

type GithubComKloudliteOperatorApisCrdsV1AppSpecContainersReadinessProbeHTTPGetIn struct {
	HTTPHeaders map[string]interface{} `json:"httpHeaders,omitempty"`
	Path        string                 `json:"path"`
	Port        int                    `json:"port"`
}

type GithubComKloudliteOperatorApisCrdsV1AppSpecContainersReadinessProbeIn struct {
	FailureThreshold *int                                                                          `json:"failureThreshold,omitempty"`
	HTTPGet          *GithubComKloudliteOperatorApisCrdsV1AppSpecContainersReadinessProbeHTTPGetIn `json:"httpGet,omitempty"`
	InitialDelay     *int                                                                          `json:"initialDelay,omitempty"`
	Interval         *int                                                                          `json:"interval,omitempty"`
	Shell            *GithubComKloudliteOperatorApisCrdsV1AppSpecContainersReadinessProbeShellIn   `json:"shell,omitempty"`
	TCP              *GithubComKloudliteOperatorApisCrdsV1AppSpecContainersReadinessProbeTCPIn     `json:"tcp,omitempty"`
	Type             string                                                                        `json:"type"`
}

type GithubComKloudliteOperatorApisCrdsV1AppSpecContainersReadinessProbeShell struct {
	Command []*string `json:"command,omitempty"`
}

type GithubComKloudliteOperatorApisCrdsV1AppSpecContainersReadinessProbeShellIn struct {
	Command []*string `json:"command,omitempty"`
}

type GithubComKloudliteOperatorApisCrdsV1AppSpecContainersReadinessProbeTCP struct {
	Port int `json:"port"`
}

type GithubComKloudliteOperatorApisCrdsV1AppSpecContainersReadinessProbeTCPIn struct {
	Port int `json:"port"`
}

type GithubComKloudliteOperatorApisCrdsV1AppSpecContainersResourceCPU struct {
	Max *string `json:"max,omitempty"`
	Min *string `json:"min,omitempty"`
}

type GithubComKloudliteOperatorApisCrdsV1AppSpecContainersResourceCPUIn struct {
	Max *string `json:"max,omitempty"`
	Min *string `json:"min,omitempty"`
}

type GithubComKloudliteOperatorApisCrdsV1AppSpecContainersResourceMemory struct {
	Max *string `json:"max,omitempty"`
	Min *string `json:"min,omitempty"`
}

type GithubComKloudliteOperatorApisCrdsV1AppSpecContainersResourceMemoryIn struct {
	Max *string `json:"max,omitempty"`
	Min *string `json:"min,omitempty"`
}

type GithubComKloudliteOperatorApisCrdsV1AppSpecContainersVolumes struct {
	Items     []*GithubComKloudliteOperatorApisCrdsV1AppSpecContainersVolumesItems `json:"items,omitempty"`
	MountPath string                                                               `json:"mountPath"`
	RefName   string                                                               `json:"refName"`
	Type      string                                                               `json:"type"`
}

type GithubComKloudliteOperatorApisCrdsV1AppSpecContainersVolumesIn struct {
	Items     []*GithubComKloudliteOperatorApisCrdsV1AppSpecContainersVolumesItemsIn `json:"items,omitempty"`
	MountPath string                                                                 `json:"mountPath"`
	RefName   string                                                                 `json:"refName"`
	Type      string                                                                 `json:"type"`
}

type GithubComKloudliteOperatorApisCrdsV1AppSpecContainersVolumesItems struct {
	FileName *string `json:"fileName,omitempty"`
	Key      string  `json:"key"`
}

type GithubComKloudliteOperatorApisCrdsV1AppSpecContainersVolumesItemsIn struct {
	FileName *string `json:"fileName,omitempty"`
	Key      string  `json:"key"`
}

type GithubComKloudliteOperatorApisCrdsV1AppSpecHpa struct {
	Enabled         *bool `json:"enabled,omitempty"`
	MaxReplicas     *int  `json:"maxReplicas,omitempty"`
	MinReplicas     *int  `json:"minReplicas,omitempty"`
	ThresholdCPU    *int  `json:"thresholdCpu,omitempty"`
	ThresholdMemory *int  `json:"thresholdMemory,omitempty"`
}

type GithubComKloudliteOperatorApisCrdsV1AppSpecHpaIn struct {
	Enabled         *bool `json:"enabled,omitempty"`
	MaxReplicas     *int  `json:"maxReplicas,omitempty"`
	MinReplicas     *int  `json:"minReplicas,omitempty"`
	ThresholdCPU    *int  `json:"thresholdCpu,omitempty"`
	ThresholdMemory *int  `json:"thresholdMemory,omitempty"`
}

type GithubComKloudliteOperatorApisCrdsV1AppSpecIntercept struct {
	Enabled  bool   `json:"enabled"`
	ToDevice string `json:"toDevice"`
}

type GithubComKloudliteOperatorApisCrdsV1AppSpecInterceptIn struct {
	Enabled  bool   `json:"enabled"`
	ToDevice string `json:"toDevice"`
}

type GithubComKloudliteOperatorApisCrdsV1AppSpecServices struct {
	Name       *string `json:"name,omitempty"`
	Port       int     `json:"port"`
	TargetPort *int    `json:"targetPort,omitempty"`
	Type       *string `json:"type,omitempty"`
}

type GithubComKloudliteOperatorApisCrdsV1AppSpecServicesIn struct {
	Name       *string `json:"name,omitempty"`
	Port       int     `json:"port"`
	TargetPort *int    `json:"targetPort,omitempty"`
	Type       *string `json:"type,omitempty"`
}

type GithubComKloudliteOperatorApisCrdsV1AppSpecTolerations struct {
	Effect            *string `json:"effect,omitempty"`
	Key               *string `json:"key,omitempty"`
	Operator          *string `json:"operator,omitempty"`
	TolerationSeconds *int    `json:"tolerationSeconds,omitempty"`
	Value             *string `json:"value,omitempty"`
}

type GithubComKloudliteOperatorApisCrdsV1AppSpecTolerationsIn struct {
	Effect            *string `json:"effect,omitempty"`
	Key               *string `json:"key,omitempty"`
	Operator          *string `json:"operator,omitempty"`
	TolerationSeconds *int    `json:"tolerationSeconds,omitempty"`
	Value             *string `json:"value,omitempty"`
}

type GithubComKloudliteOperatorApisCrdsV1ManagedResourceSpecMresKind struct {
	Kind string `json:"kind"`
}

type GithubComKloudliteOperatorApisCrdsV1ManagedResourceSpecMresKindIn struct {
	Kind string `json:"kind"`
}

type GithubComKloudliteOperatorApisCrdsV1ManagedResourceSpecMsvcRef struct {
	APIVersion string  `json:"apiVersion"`
	Kind       *string `json:"kind,omitempty"`
	Name       string  `json:"name"`
}

type GithubComKloudliteOperatorApisCrdsV1ManagedResourceSpecMsvcRefIn struct {
	APIVersion string  `json:"apiVersion"`
	Kind       *string `json:"kind,omitempty"`
	Name       string  `json:"name"`
}

type GithubComKloudliteOperatorApisCrdsV1ManagedServiceSpecMsvcKind struct {
	APIVersion string  `json:"apiVersion"`
	Kind       *string `json:"kind,omitempty"`
}

type GithubComKloudliteOperatorApisCrdsV1ManagedServiceSpecMsvcKindIn struct {
	APIVersion string  `json:"apiVersion"`
	Kind       *string `json:"kind,omitempty"`
}

type GithubComKloudliteOperatorApisCrdsV1ManagedServiceSpecTolerations struct {
	Effect            *string `json:"effect,omitempty"`
	Key               *string `json:"key,omitempty"`
	Operator          *string `json:"operator,omitempty"`
	TolerationSeconds *int    `json:"tolerationSeconds,omitempty"`
	Value             *string `json:"value,omitempty"`
}

type GithubComKloudliteOperatorApisCrdsV1ManagedServiceSpecTolerationsIn struct {
	Effect            *string `json:"effect,omitempty"`
	Key               *string `json:"key,omitempty"`
	Operator          *string `json:"operator,omitempty"`
	TolerationSeconds *int    `json:"tolerationSeconds,omitempty"`
	Value             *string `json:"value,omitempty"`
}

type GithubComKloudliteOperatorApisCrdsV1RouterSpecBasicAuth struct {
	Enabled    bool    `json:"enabled"`
	SecretName *string `json:"secretName,omitempty"`
	Username   *string `json:"username,omitempty"`
}

type GithubComKloudliteOperatorApisCrdsV1RouterSpecBasicAuthIn struct {
	Enabled    bool    `json:"enabled"`
	SecretName *string `json:"secretName,omitempty"`
	Username   *string `json:"username,omitempty"`
}

type GithubComKloudliteOperatorApisCrdsV1RouterSpecCors struct {
	AllowCredentials *bool     `json:"allowCredentials,omitempty"`
	Enabled          *bool     `json:"enabled,omitempty"`
	Origins          []*string `json:"origins,omitempty"`
}

type GithubComKloudliteOperatorApisCrdsV1RouterSpecCorsIn struct {
	AllowCredentials *bool     `json:"allowCredentials,omitempty"`
	Enabled          *bool     `json:"enabled,omitempty"`
	Origins          []*string `json:"origins,omitempty"`
}

type GithubComKloudliteOperatorApisCrdsV1RouterSpecHTTPS struct {
	ClusterIssuer *string `json:"clusterIssuer,omitempty"`
	Enabled       bool    `json:"enabled"`
	ForceRedirect *bool   `json:"forceRedirect,omitempty"`
}

type GithubComKloudliteOperatorApisCrdsV1RouterSpecHTTPSIn struct {
	ClusterIssuer *string `json:"clusterIssuer,omitempty"`
	Enabled       bool    `json:"enabled"`
	ForceRedirect *bool   `json:"forceRedirect,omitempty"`
}

type GithubComKloudliteOperatorApisCrdsV1RouterSpecRateLimit struct {
	Connections *int  `json:"connections,omitempty"`
	Enabled     *bool `json:"enabled,omitempty"`
	Rpm         *int  `json:"rpm,omitempty"`
	Rps         *int  `json:"rps,omitempty"`
}

type GithubComKloudliteOperatorApisCrdsV1RouterSpecRateLimitIn struct {
	Connections *int  `json:"connections,omitempty"`
	Enabled     *bool `json:"enabled,omitempty"`
	Rpm         *int  `json:"rpm,omitempty"`
	Rps         *int  `json:"rps,omitempty"`
}

type GithubComKloudliteOperatorApisCrdsV1RouterSpecRoutes struct {
	App     *string `json:"app,omitempty"`
	Lambda  *string `json:"lambda,omitempty"`
	Path    string  `json:"path"`
	Port    int     `json:"port"`
	Rewrite *bool   `json:"rewrite,omitempty"`
}

type GithubComKloudliteOperatorApisCrdsV1RouterSpecRoutesIn struct {
	App     *string `json:"app,omitempty"`
	Lambda  *string `json:"lambda,omitempty"`
	Path    string  `json:"path"`
	Port    int     `json:"port"`
	Rewrite *bool   `json:"rewrite,omitempty"`
}

type GithubComKloudliteOperatorPkgOperatorCheck struct {
	Generation *int    `json:"generation,omitempty"`
	Message    *string `json:"message,omitempty"`
	Status     bool    `json:"status"`
}

type GithubComKloudliteOperatorPkgOperatorCheckIn struct {
	Generation *int    `json:"generation,omitempty"`
	Message    *string `json:"message,omitempty"`
	Status     bool    `json:"status"`
}

type GithubComKloudliteOperatorPkgOperatorResourceRef struct {
	Name      string `json:"name"`
	Namespace string `json:"namespace"`
}

type GithubComKloudliteOperatorPkgOperatorResourceRefIn struct {
	Name      string `json:"name"`
	Namespace string `json:"namespace"`
}

type GithubComKloudliteOperatorPkgRawJSONRawJSON struct {
	RawMessage interface{} `json:"RawMessage,omitempty"`
}

type GithubComKloudliteOperatorPkgRawJSONRawJSONIn struct {
	RawMessage interface{} `json:"RawMessage,omitempty"`
}

type KloudliteIoAppsConsoleInternalDomainEntitiesInputField struct {
	DefaultValue interface{} `json:"defaultValue"`
	InputType    string      `json:"inputType"`
	Label        string      `json:"label"`
	Max          *float64    `json:"max,omitempty"`
	Min          *float64    `json:"min,omitempty"`
	Name         string      `json:"name"`
	Required     *bool       `json:"required,omitempty"`
	Unit         *string     `json:"unit,omitempty"`
}

type KloudliteIoAppsConsoleInternalDomainEntitiesInputFieldIn struct {
	DefaultValue interface{} `json:"defaultValue"`
	InputType    string      `json:"inputType"`
	Label        string      `json:"label"`
	Max          *float64    `json:"max,omitempty"`
	Min          *float64    `json:"min,omitempty"`
	Name         string      `json:"name"`
	Required     *bool       `json:"required,omitempty"`
	Unit         *string     `json:"unit,omitempty"`
}

type KloudliteIoAppsConsoleInternalDomainEntitiesMresTemplate struct {
	Description string                                                     `json:"description"`
	DisplayName string                                                     `json:"displayName"`
	Fields      []*KloudliteIoAppsConsoleInternalDomainEntitiesInputField  `json:"fields"`
	Name        string                                                     `json:"name"`
	Outputs     []*KloudliteIoAppsConsoleInternalDomainEntitiesOutputField `json:"outputs"`
}

type KloudliteIoAppsConsoleInternalDomainEntitiesMresTemplateIn struct {
	Description string                                                       `json:"description"`
	DisplayName string                                                       `json:"displayName"`
	Fields      []*KloudliteIoAppsConsoleInternalDomainEntitiesInputFieldIn  `json:"fields"`
	Name        string                                                       `json:"name"`
	Outputs     []*KloudliteIoAppsConsoleInternalDomainEntitiesOutputFieldIn `json:"outputs"`
}

type KloudliteIoAppsConsoleInternalDomainEntitiesMsvcTemplateEntry struct {
	Active      bool                                                        `json:"active"`
	Description string                                                      `json:"description"`
	DisplayName string                                                      `json:"displayName"`
	Fields      []*KloudliteIoAppsConsoleInternalDomainEntitiesInputField   `json:"fields"`
	LogoURL     string                                                      `json:"logoUrl"`
	Name        string                                                      `json:"name"`
	Outputs     []*KloudliteIoAppsConsoleInternalDomainEntitiesOutputField  `json:"outputs"`
	Resources   []*KloudliteIoAppsConsoleInternalDomainEntitiesMresTemplate `json:"resources"`
}

type KloudliteIoAppsConsoleInternalDomainEntitiesMsvcTemplateEntryIn struct {
	Active      bool                                                          `json:"active"`
	Description string                                                        `json:"description"`
	DisplayName string                                                        `json:"displayName"`
	Fields      []*KloudliteIoAppsConsoleInternalDomainEntitiesInputFieldIn   `json:"fields"`
	LogoURL     string                                                        `json:"logoUrl"`
	Name        string                                                        `json:"name"`
	Outputs     []*KloudliteIoAppsConsoleInternalDomainEntitiesOutputFieldIn  `json:"outputs"`
	Resources   []*KloudliteIoAppsConsoleInternalDomainEntitiesMresTemplateIn `json:"resources"`
}

type KloudliteIoAppsConsoleInternalDomainEntitiesOutputField struct {
	Description string `json:"description"`
	Label       string `json:"label"`
	Name        string `json:"name"`
}

type KloudliteIoAppsConsoleInternalDomainEntitiesOutputFieldIn struct {
	Description string `json:"description"`
	Label       string `json:"label"`
	Name        string `json:"name"`
}

type MsvcTemplate struct {
	Category    string                                                           `json:"category"`
	DisplayName string                                                           `json:"displayName"`
	Items       []*KloudliteIoAppsConsoleInternalDomainEntitiesMsvcTemplateEntry `json:"items"`
}

type MsvcTemplateIn struct {
	Category    string                                                             `json:"category"`
	DisplayName string                                                             `json:"displayName"`
	Items       []*KloudliteIoAppsConsoleInternalDomainEntitiesMsvcTemplateEntryIn `json:"items"`
}
