// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/kloudlite/api/pkg/repos"
)

type GithubComKloudliteAPICommonCreatedOrUpdatedBy struct {
	UserEmail string `json:"userEmail"`
	UserID    string `json:"userId"`
	UserName  string `json:"userName"`
}

type Mutation struct {
}

type PageInfo struct {
	EndCursor   *string `json:"endCursor,omitempty"`
	HasNextPage *bool   `json:"hasNextPage,omitempty"`
	HasPrevPage *bool   `json:"hasPrevPage,omitempty"`
	StartCursor *string `json:"startCursor,omitempty"`
}

type Query struct {
}

type Uses struct {
	CreationTime      string   `json:"creationTime"`
	ID                repos.ID `json:"id"`
	MarkedForDeletion *bool    `json:"markedForDeletion,omitempty"`
	RecordVersion     int      `json:"recordVersion"`
	UpdateTime        string   `json:"updateTime"`
}
