package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.28

import (
	"context"
	"fmt"

	"github.com/kloudlite/api/apps/infra/internal/app/graph/generated"
	"github.com/kloudlite/api/apps/infra/internal/app/graph/model"
	"github.com/kloudlite/api/apps/infra/internal/entities"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
)

// CreationTime is the resolver for the creationTime field.
func (r *namespaceResolver) CreationTime(ctx context.Context, obj *entities.Namespace) (string, error) {
	panic(fmt.Errorf("not implemented: CreationTime - creationTime"))
}

// ID is the resolver for the id field.
func (r *namespaceResolver) ID(ctx context.Context, obj *entities.Namespace) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// Spec is the resolver for the spec field.
func (r *namespaceResolver) Spec(ctx context.Context, obj *entities.Namespace) (*model.K8sIoAPICoreV1NamespaceSpec, error) {
	panic(fmt.Errorf("not implemented: Spec - spec"))
}

// Status is the resolver for the status field.
func (r *namespaceResolver) Status(ctx context.Context, obj *entities.Namespace) (*model.K8sIoAPICoreV1NamespaceStatus, error) {
	panic(fmt.Errorf("not implemented: Status - status"))
}

// UpdateTime is the resolver for the updateTime field.
func (r *namespaceResolver) UpdateTime(ctx context.Context, obj *entities.Namespace) (string, error) {
	panic(fmt.Errorf("not implemented: UpdateTime - updateTime"))
}

// Metadata is the resolver for the metadata field.
func (r *namespaceInResolver) Metadata(ctx context.Context, obj *entities.Namespace, data *v1.ObjectMeta) error {
	panic(fmt.Errorf("not implemented: Metadata - metadata"))
}

// Spec is the resolver for the spec field.
func (r *namespaceInResolver) Spec(ctx context.Context, obj *entities.Namespace, data *model.K8sIoAPICoreV1NamespaceSpecIn) error {
	panic(fmt.Errorf("not implemented: Spec - spec"))
}

// Status is the resolver for the status field.
func (r *namespaceInResolver) Status(ctx context.Context, obj *entities.Namespace, data *model.K8sIoAPICoreV1NamespaceStatusIn) error {
	panic(fmt.Errorf("not implemented: Status - status"))
}

// Namespace returns generated.NamespaceResolver implementation.
func (r *Resolver) Namespace() generated.NamespaceResolver { return &namespaceResolver{r} }

// NamespaceIn returns generated.NamespaceInResolver implementation.
func (r *Resolver) NamespaceIn() generated.NamespaceInResolver { return &namespaceInResolver{r} }

type (
	namespaceResolver   struct{ *Resolver }
	namespaceInResolver struct{ *Resolver }
)

