package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.28

import (
	"context"
	"fmt"

	"github.com/kloudlite/api/apps/infra/internal/app/graph/generated"
	"github.com/kloudlite/api/apps/infra/internal/app/graph/model"
	"github.com/kloudlite/api/apps/infra/internal/entities"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
)

// CreationTime is the resolver for the creationTime field.
func (r *persistentVolumeResolver) CreationTime(ctx context.Context, obj *entities.PersistentVolume) (string, error) {
	panic(fmt.Errorf("not implemented: CreationTime - creationTime"))
}

// ID is the resolver for the id field.
func (r *persistentVolumeResolver) ID(ctx context.Context, obj *entities.PersistentVolume) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// Spec is the resolver for the spec field.
func (r *persistentVolumeResolver) Spec(ctx context.Context, obj *entities.PersistentVolume) (*model.K8sIoAPICoreV1PersistentVolumeSpec, error) {
	panic(fmt.Errorf("not implemented: Spec - spec"))
}

// Status is the resolver for the status field.
func (r *persistentVolumeResolver) Status(ctx context.Context, obj *entities.PersistentVolume) (*model.K8sIoAPICoreV1PersistentVolumeStatus, error) {
	panic(fmt.Errorf("not implemented: Status - status"))
}

// UpdateTime is the resolver for the updateTime field.
func (r *persistentVolumeResolver) UpdateTime(ctx context.Context, obj *entities.PersistentVolume) (string, error) {
	panic(fmt.Errorf("not implemented: UpdateTime - updateTime"))
}

// Metadata is the resolver for the metadata field.
func (r *persistentVolumeInResolver) Metadata(ctx context.Context, obj *entities.PersistentVolume, data *v1.ObjectMeta) error {
	panic(fmt.Errorf("not implemented: Metadata - metadata"))
}

// Spec is the resolver for the spec field.
func (r *persistentVolumeInResolver) Spec(ctx context.Context, obj *entities.PersistentVolume, data *model.K8sIoAPICoreV1PersistentVolumeSpecIn) error {
	panic(fmt.Errorf("not implemented: Spec - spec"))
}

// Status is the resolver for the status field.
func (r *persistentVolumeInResolver) Status(ctx context.Context, obj *entities.PersistentVolume, data *model.K8sIoAPICoreV1PersistentVolumeStatusIn) error {
	panic(fmt.Errorf("not implemented: Status - status"))
}

// PersistentVolume returns generated.PersistentVolumeResolver implementation.
func (r *Resolver) PersistentVolume() generated.PersistentVolumeResolver {
	return &persistentVolumeResolver{r}
}

// PersistentVolumeIn returns generated.PersistentVolumeInResolver implementation.
func (r *Resolver) PersistentVolumeIn() generated.PersistentVolumeInResolver {
	return &persistentVolumeInResolver{r}
}

type persistentVolumeResolver struct{ *Resolver }
type persistentVolumeInResolver struct{ *Resolver }
