package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	"context"
	"fmt"
	"github.com/kloudlite/api/pkg/errors"
	"time"

	"github.com/kloudlite/api/apps/infra/internal/app/graph/generated"
	"github.com/kloudlite/api/apps/infra/internal/app/graph/model"
	"github.com/kloudlite/api/apps/infra/internal/entities"
	"github.com/kloudlite/api/pkg/repos"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
)

// CreationTime is the resolver for the creationTime field.
func (r *workspaceResolver) CreationTime(ctx context.Context, obj *entities.Workspace) (string, error) {
	if obj == nil {
		return "", errors.Newf("workspace obj is nil")
	}
	return obj.CreationTime.Format(time.RFC3339), nil
}

// ID is the resolver for the id field.
func (r *workspaceResolver) ID(ctx context.Context, obj *entities.Workspace) (repos.ID, error) {
	if obj == nil {
		return "", errors.Newf("workspace obj is nil")
	}
	return obj.Id, nil
}

// Spec is the resolver for the spec field.
func (r *workspaceResolver) Spec(ctx context.Context, obj *entities.Workspace) (*model.GithubComKloudliteOperatorApisCrdsV1WorkspaceSpec, error) {
	panic(fmt.Errorf("not implemented: Spec - spec"))
}

// UpdateTime is the resolver for the updateTime field.
func (r *workspaceResolver) UpdateTime(ctx context.Context, obj *entities.Workspace) (string, error) {
	if obj == nil || obj.UpdateTime.IsZero() {
		return "", errors.Newf("workspace is nil")
	}
	return obj.UpdateTime.Format(time.RFC3339), nil
}

// Metadata is the resolver for the metadata field.
func (r *workspaceInResolver) Metadata(ctx context.Context, obj *entities.Workspace, data *v1.ObjectMeta) error {
	panic(fmt.Errorf("not implemented: Metadata - metadata"))
}

// Spec is the resolver for the spec field.
func (r *workspaceInResolver) Spec(ctx context.Context, obj *entities.Workspace, data *model.GithubComKloudliteOperatorApisCrdsV1WorkspaceSpecIn) error {
	panic(fmt.Errorf("not implemented: Spec - spec"))
}

// Status is the resolver for the status field.
func (r *workspaceInResolver) Status(ctx context.Context, obj *entities.Workspace, data *model.GithubComKloudliteOperatorToolkitReconcilerStatusIn) error {
	panic(fmt.Errorf("not implemented: Status - status"))
}

// Workspace returns generated.WorkspaceResolver implementation.
func (r *Resolver) Workspace() generated.WorkspaceResolver { return &workspaceResolver{r} }

// WorkspaceIn returns generated.WorkspaceInResolver implementation.
func (r *Resolver) WorkspaceIn() generated.WorkspaceInResolver { return &workspaceInResolver{r} }

type workspaceResolver struct{ *Resolver }
type workspaceInResolver struct{ *Resolver }
