package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	"context"
	"github.com/kloudlite/api/pkg/errors"
	"time"

	"github.com/kloudlite/api/apps/infra/internal/app/graph/generated"
	"github.com/kloudlite/api/apps/infra/internal/entities"
	"github.com/kloudlite/api/pkg/repos"
)

// CreationTime is the resolver for the creationTime field.
func (r *workmachineResolver) CreationTime(ctx context.Context, obj *entities.Workmachine) (string, error) {
	if obj == nil {
		return "", errors.Newf("workmachine obj is nil")
	}
	return obj.CreationTime.Format(time.RFC3339), nil
}

// ID is the resolver for the id field.
func (r *workmachineResolver) ID(ctx context.Context, obj *entities.Workmachine) (repos.ID, error) {
	if obj == nil {
		return "", errors.Newf("workmachine obj is nil")
	}
	return obj.Id, nil
}

// UpdateTime is the resolver for the updateTime field.
func (r *workmachineResolver) UpdateTime(ctx context.Context, obj *entities.Workmachine) (string, error) {
	if obj == nil || obj.UpdateTime.IsZero() {
		return "", errors.Newf("workmachine is nil")
	}
	return obj.UpdateTime.Format(time.RFC3339), nil
}

// Workmachine returns generated.WorkmachineResolver implementation.
func (r *Resolver) Workmachine() generated.WorkmachineResolver { return &workmachineResolver{r} }

type workmachineResolver struct{ *Resolver }
