name: Builds

on:
  workflow_run:
    workflows: [ "Install Go Mod" ]
    types:
      - completed

jobs:
  build:
    name: Image Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app:
          - auth
          - finance
          - container-registry
          - dns
          - gateway
          - iam
#          - js-eval
          - message-office
          - infra
          - webhooks
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: '^1.19.3'

      - name: Setup Docker
        id: setup
        uses: ./.github/actions/setup
        with:
          app: ${{ matrix.app }}
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - shell: bash
        run: |
          cd apps/${{ matrix.app }}
          go build -o ${{ matrix.app }}

      - name: Build & Push Image
        env:
          REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          APP: ${{ matrix.app }}
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        run: |
          docker buildx build . -t ${REGISTRY}/kloudlite/${APP}:${{ steps.setup.outputs.image-tag }} --push --build-arg APP=${APP}
