name: build/Container Builds

on:
  workflow_dispatch:
    inputs:
      image-tag:
        description: 'Image Tag'
        required: true

  push:
    branches:
      - main
      - issue/**
      - feature/**
      - bug/**

jobs:
  build:
    name: Building Container Image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app:
          - auth
          - finance
          - container-registry
          - dns
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Docker
        id: setup
        uses: ./.github/actions/setup
        with:
          app: ${{ matrix.app }}
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Image
        env:
          REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          APP: ${{ matrix.app }}
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        run: |
          docker buildx build -f ./apps/${APP}/Dockerfile -t ${REGISTRY}/kloudlite/${APP}:${{ steps.setup.outputs.image-tag }} --push --build-arg APP=${APP} --build-arg GH_ACCESS_TOKEN=${GH_ACCESS_TOKEN} --build-context project-root=. --cache-from type=local,src=/docker-cache --cache-to type=local,dest=/docker-cache ./apps/${APP}
