name: Build & Publish


on:
  workflow_dispatch:

jobs:
  build:
    name: Deploy to Docker Image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app:
          - auth
          - finance
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Release App
        env:
          REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          APP: ${{ matrix.app }}
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        run: docker buildx build -f ./apps/${APP}/Dockerfile -t ${REGISTRY}/kloudlite/${APP}:${{ steps.tag.outputs.docker-tag }} ./apps/${APP} --push --build-arg APP=${APP} --build-arg GH_ACCESS_TOKEN=${GH_ACCESS_TOKEN} --build-context project-root=.
