name: Build & Publish


on:
  workflow_dispatch:


jobs:
  build:
    name: Deploy to Docker Image
    steps:

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Docker tag
        id: tag
        uses: cytopia/docker-tag-action@v0.4.7

      - name: Release Auth
        env:
          REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          APP: auth
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        run: docker buildx build -f ./apps/${APP}/Dockerfile -t ${REGISTRY}/kloudlite/${APP}:${{ steps.tag.outputs.docker-tag }} ./apps/${APP} --push --build-arg APP=${APP} --build-arg GH_ACCESS_TOKEN=${GH_ACCESS_TOKEN} --build-context project-root=.

      - name: Release Finance
        env:
          REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          APP: finance
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        run: docker buildx build -f ./apps/${APP}/Dockerfile -t ${REGISTRY}/kloudlite/${APP}:${{ steps.tag.outputs.docker-tag }} ./apps/${APP} --push --build-arg APP=${APP} --build-arg GH_ACCESS_TOKEN=${GH_ACCESS_TOKEN} --build-context project-root=.
