name: Install Go Mod

on:
  workflow_dispatch:
    inputs:
      image-tag:
        description: 'Image Tag'
        required: true

  push:
    branches:
      - main
      - issue/**
      - feature/**
      - bug/**

jobs:
  install:
    name: Download Go Modules
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/kloudlite/operator,github.com/kloudlite/wg-operator,github.com/kloudlite/cluster-operator
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: '^1.19.3'

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - shell: bash
        run: |
          go mod download -x
