package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.28

import (
	"context"
	"fmt"
	"time"

	"kloudlite.io/apps/console/internal/app/graph/generated"
	"kloudlite.io/apps/console/internal/domain/entities"
)

// CreationTime is the resolver for the creationTime field.
func (r *imagePullSecretResolver) CreationTime(ctx context.Context, obj *entities.ImagePullSecret) (string, error) {
	if obj == nil {
		return "", fmt.Errorf("obj is nil")
	}
	return obj.CreationTime.Format(time.RFC3339), nil
}

// ID is the resolver for the id field.
func (r *imagePullSecretResolver) ID(ctx context.Context, obj *entities.ImagePullSecret) (string, error) {
	if obj == nil {
		return "", fmt.Errorf("obj is nil")
	}
	return string(obj.Id), nil
}

// UpdateTime is the resolver for the updateTime field.
func (r *imagePullSecretResolver) UpdateTime(ctx context.Context, obj *entities.ImagePullSecret) (string, error) {
	if obj == nil {
		return "", fmt.Errorf("obj is nil")
	}
	return obj.UpdateTime.Format(time.RFC3339), nil
}

// ImagePullSecret returns generated.ImagePullSecretResolver implementation.
func (r *Resolver) ImagePullSecret() generated.ImagePullSecretResolver {
	return &imagePullSecretResolver{r}
}

type imagePullSecretResolver struct{ *Resolver }
