package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.28

import (
	"context"

	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"kloudlite.io/apps/console/internal/app/graph/generated"
	"kloudlite.io/apps/console/internal/domain/entities"
)

// Metadata is the resolver for the metadata field.
func (r *managedServiceInResolver) Metadata(ctx context.Context, obj *entities.ManagedService, data *v1.ObjectMeta) error {
	obj.ObjectMeta = *data
	return nil
}

// ManagedServiceIn returns generated.ManagedServiceInResolver implementation.
func (r *Resolver) ManagedServiceIn() generated.ManagedServiceInResolver {
	return &managedServiceInResolver{r}
}

type managedServiceInResolver struct{ *Resolver }
