package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.28

import (
	"context"

	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"kloudlite.io/apps/console/internal/app/graph/generated"
	"kloudlite.io/apps/console/internal/domain/entities"
)

// Metadata is the resolver for the metadata field.
func (r *projectInResolver) Metadata(ctx context.Context, obj *entities.Project, data *v1.ObjectMeta) error {
	obj.ObjectMeta = *data
	return nil
}

// ProjectIn returns generated.ProjectInResolver implementation.
func (r *Resolver) ProjectIn() generated.ProjectInResolver { return &projectInResolver{r} }

type projectInResolver struct{ *Resolver }
