package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	"context"
	"fmt"
	"github.com/kloudlite/api/pkg/errors"
	"time"

	"github.com/kloudlite/api/apps/console/internal/app/graph/generated"
	"github.com/kloudlite/api/apps/console/internal/app/graph/model"
	"github.com/kloudlite/api/apps/console/internal/entities"
	fn "github.com/kloudlite/api/pkg/functions"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
)

// CreationTime is the resolver for the creationTime field.
func (r *serviceBindingResolver) CreationTime(ctx context.Context, obj *entities.ServiceBinding) (string, error) {
	if obj == nil {
		return "", errNilServiceBinding
	}
	return obj.BaseEntity.CreationTime.Format(time.RFC3339), nil
}

// Spec is the resolver for the spec field.
func (r *serviceBindingResolver) Spec(ctx context.Context, obj *entities.ServiceBinding) (*model.GithubComKloudliteOperatorApisNetworkingV1ServiceBindingSpec, error) {
	m := model.GithubComKloudliteOperatorApisNetworkingV1ServiceBindingSpec{}
	if err := fn.JsonConversion(obj.Spec, &m); err != nil {
		return nil, errors.NewE(err)
	}
	return &m, nil
}

// UpdateTime is the resolver for the updateTime field.
func (r *serviceBindingResolver) UpdateTime(ctx context.Context, obj *entities.ServiceBinding) (string, error) {
	if obj == nil {
		return "", errors.Newf("obj is nil")
	}

	return obj.BaseEntity.UpdateTime.Format(time.RFC3339), nil
}

// CreationTime is the resolver for the creationTime field.
func (r *serviceBindingInResolver) CreationTime(ctx context.Context, obj *entities.ServiceBinding, data string) error {
	panic(fmt.Errorf("not implemented: CreationTime - creationTime"))
}

// Metadata is the resolver for the metadata field.
func (r *serviceBindingInResolver) Metadata(ctx context.Context, obj *entities.ServiceBinding, data *v1.ObjectMeta) error {
	panic(fmt.Errorf("not implemented: Metadata - metadata"))
}

// Spec is the resolver for the spec field.
func (r *serviceBindingInResolver) Spec(ctx context.Context, obj *entities.ServiceBinding, data *model.GithubComKloudliteOperatorApisNetworkingV1ServiceBindingSpecIn) error {
	if obj == nil {
		return errNilServiceBinding
	}
	return fn.JsonConversion(data, &obj.Spec)
}

// Status is the resolver for the status field.
func (r *serviceBindingInResolver) Status(ctx context.Context, obj *entities.ServiceBinding, data *model.GithubComKloudliteOperatorPkgOperatorStatusIn) error {
	panic(fmt.Errorf("not implemented: Status - status"))
}

// UpdateTime is the resolver for the updateTime field.
func (r *serviceBindingInResolver) UpdateTime(ctx context.Context, obj *entities.ServiceBinding, data string) error {
	panic(fmt.Errorf("not implemented: UpdateTime - updateTime"))
}

// ServiceBinding returns generated.ServiceBindingResolver implementation.
func (r *Resolver) ServiceBinding() generated.ServiceBindingResolver {
	return &serviceBindingResolver{r}
}

// ServiceBindingIn returns generated.ServiceBindingInResolver implementation.
func (r *Resolver) ServiceBindingIn() generated.ServiceBindingInResolver {
	return &serviceBindingInResolver{r}
}

type serviceBindingResolver struct{ *Resolver }
type serviceBindingInResolver struct{ *Resolver }
