package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.28

import (
	"context"
	"fmt"

	"github.com/kloudlite/api/apps/console/internal/app/graph/generated"
	"github.com/kloudlite/api/apps/console/internal/app/graph/model"
	"github.com/kloudlite/api/apps/console/internal/entities"
	"github.com/kloudlite/api/pkg/types"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
)

// CreationTime is the resolver for the creationTime field.
func (r *vPNDeviceResolver) CreationTime(ctx context.Context, obj *entities.VPNDevice) (string, error) {
	panic(fmt.Errorf("not implemented: CreationTime - creationTime"))
}

// ID is the resolver for the id field.
func (r *vPNDeviceResolver) ID(ctx context.Context, obj *entities.VPNDevice) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// Spec is the resolver for the spec field.
func (r *vPNDeviceResolver) Spec(ctx context.Context, obj *entities.VPNDevice) (*model.GithubComKloudliteOperatorApisWireguardV1DeviceSpec, error) {
	panic(fmt.Errorf("not implemented: Spec - spec"))
}

// SyncStatus is the resolver for the syncStatus field.
func (r *vPNDeviceResolver) SyncStatus(ctx context.Context, obj *entities.VPNDevice) (*types.SyncStatus, error) {
	panic(fmt.Errorf("not implemented: SyncStatus - syncStatus"))
}

// UpdateTime is the resolver for the updateTime field.
func (r *vPNDeviceResolver) UpdateTime(ctx context.Context, obj *entities.VPNDevice) (string, error) {
	panic(fmt.Errorf("not implemented: UpdateTime - updateTime"))
}

// WireguardConfig is the resolver for the wireguardConfig field.
func (r *vPNDeviceResolver) WireguardConfig(ctx context.Context, obj *entities.VPNDevice) (*model.GithubComKloudliteAPIPkgTypesEncodedString, error) {
	panic(fmt.Errorf("not implemented: WireguardConfig - wireguardConfig"))
}

// Metadata is the resolver for the metadata field.
func (r *vPNDeviceInResolver) Metadata(ctx context.Context, obj *entities.VPNDevice, data *v1.ObjectMeta) error {
	panic(fmt.Errorf("not implemented: Metadata - metadata"))
}

// Spec is the resolver for the spec field.
func (r *vPNDeviceInResolver) Spec(ctx context.Context, obj *entities.VPNDevice, data *model.GithubComKloudliteOperatorApisWireguardV1DeviceSpecIn) error {
	panic(fmt.Errorf("not implemented: Spec - spec"))
}

// VPNDevice returns generated.VPNDeviceResolver implementation.
func (r *Resolver) VPNDevice() generated.VPNDeviceResolver { return &vPNDeviceResolver{r} }

// VPNDeviceIn returns generated.VPNDeviceInResolver implementation.
func (r *Resolver) VPNDeviceIn() generated.VPNDeviceInResolver { return &vPNDeviceInResolver{r} }

type vPNDeviceResolver struct{ *Resolver }
type vPNDeviceInResolver struct{ *Resolver }
