package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.28

import (
	"context"
	"fmt"

	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"kloudlite.io/apps/console/internal/app/graph/generated"
	"kloudlite.io/apps/console/internal/domain/entities"
)

// Metadata is the resolver for the metadata field.
func (r *workspaceInResolver) Metadata(ctx context.Context, obj *entities.Workspace, data *v1.ObjectMeta) error {
	if data != nil {
		obj.ObjectMeta = *data
		return nil
	}
	return fmt.Errorf("data is nil")
}

// WorkspaceIn returns generated.WorkspaceInResolver implementation.
func (r *Resolver) WorkspaceIn() generated.WorkspaceInResolver { return &workspaceInResolver{r} }

type workspaceInResolver struct{ *Resolver }
